### ISSUE TITLE
installing kaspa-wallet with npm dependency issues

### ISSUE THREAD

**Issue by demisrael** [aspectron/kaspa-wallet#1]
followed your instructions, I did run npm install on my machine where nodejs never seen in past and got following error (dependencys?)

$ kaspa-wallet help
/usr/lib/node_modules/@kaspa/wallet-cli/kaspa-wallet.js:48
errorCB?.(count)
^

SyntaxError: Unexpected token .
at createScript (vm.js:56:10)
at Object.runInThisContext (vm.js:97:10)
at Module._compile (module.js:549:28)
at Object.Module._extensions..js (module.js:586:10)
at Module.load (module.js:494:32)
at tryModuleLoad (module.js:453:12)
at Function.Module._load (module.js:445:3)
at Module.runMain (module.js:611:10)
at run (bootstrap_node.js:394:7)
at startup (bootstrap_node.js:160:9)

**Comment by aspect** [comment]
hm... somehow I haven't seen a notification for this issue.  I am sure it's been resolved by now, if not, please reopen.
